services:
  php:
    build: .
    ports:
      - "9003:9003"
    volumes:
      - ./:/var/www/html:rw,cached
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    command: bash -c "php -S 0.0.0.0:8000 -t /var/www/html"

  composer:
    image: composer/composer
    working_dir: /var/www/html
    environment:
      - COMPOSER_ALLOW_SUPER_USER=1
    volumes:
      - ./:/var/www/html:rw,cached